### ISSUE TITLE
onHeadingChange is not defined , strapi V 4.1.5  strapi-tiptap-editor 0.7.2

### ISSUE THREAD

**Issue by giuseppegatto** [dasmikko/strapi-tiptap-editor#10]
hi, 
when i try to choose something different to paragaph 
![image](https://user-images.githubusercontent.com/81235671/159461970-d8c8589e-2e84-46f8-8732-c5a16188b376.png)
i get this error
![image](https://user-images.githubusercontent.com/81235671/159462138-8a8c4ba0-1c73-4260-ab33-0c4ef6be5f8b.png)

**Comment by dasmikko** [comment]
Oh sorry about that!

It has been fixed in 0.7.3, that is available now.
