### ISSUE TITLE
black font color with new DarkTheme

### ISSUE THREAD

**Issue by Th3vanger** [dasmikko/strapi-tiptap-editor#11]
hello, 
The font color or the text area with the new dark theme of strapi is black and it is not very readable
<img width="808" alt="image" src="https://user-images.githubusercontent.com/57135668/161215935-6a1a31f8-a56e-42e0-83d3-80917dc8efd8.png">

**Comment by mrcnk** [comment]
Added a simple workaround to fix it in #12.

**Comment by dasmikko** [comment]
Thanks for the fix @mrcnk !

I have merged your changes, and fixed the small bug it contained. 👍🏻 

It has been released in version 0.7.4
