### ISSUE TITLE
[bug] Internationalization is back

### ISSUE THREAD

**Issue by ABlok89** [dasmikko/strapi-tiptap-editor#14]
The bug with Internationalization  is back. See #4 
Tested with 0.7.3 and 0.7.7.
When i refresh the page the good content is shown.

Can you also show the world icon when Internationalization is enabled.

**Comment by dasmikko** [comment]
Hmm, I'm having issues replicating the issue.

I'm running the latest version of strapi and my plugin.

I will look into adding the world icon.

**Comment by dasmikko** [comment]
The icon is now correctly implemented in 0.7.8.

![image](https://user-images.githubusercontent.com/4254869/164393874-49847b43-4aac-42f2-b411-d0a2135b2db8.png)

I'm still struggling with replicating your issue. Could you maybe make a small video, or a project that I test myself?

**Comment by ABlok89** [comment]
I made a video: https://files.fm/u/au4p2tymk

**Comment by dasmikko** [comment]
No problem with the icon 👍

Here is a video of my test site.
https://files.fm/u/cwk6n3ptz#/view/amf4czszu

Same strapi version. I've got no clue why this is only happening to you. 

Anybody else experiencing this issue?

**Comment by ABlok89** [comment]
I have a clean install and use postgres.
The version of i18n is 4.1.8.
Strange that you can't reproduce it.

**Comment by ABlok89** [comment]
Problem only exsist with Single Types.
With collection type i don't have problems.

**Comment by dasmikko** [comment]
Ok, now I can replicate the issue. 

Odd that the issue is only for Single Types.

**Comment by dasmikko** [comment]
Issue is now fixed in version 0.7.9. 🥳
