### ISSUE TITLE
[Suggestion] Adding a word count

### ISSUE THREAD

**Issue by JoshuaOyewole** [dasmikko/strapi-tiptap-editor#18]
As a blogger who is using Strapi CMS for my backend with your Plugin installed.
I feel having the word count displayed on the right-hand side will help us to know the length of our content with ease and this will help to boost other writer's speed who are trying to write a certain amount of characters/word count.

I look forward to seeing this implemented in the next update.
Best Regards
[Joshua Oyewole](https://beginnerswebguide.com)

**Comment by dasmikko** [comment]
This is now implemented in 0.7.10
