### ISSUE TITLE
Crashes since v4.1.10

### ISSUE THREAD

**Issue by afroborg** [dasmikko/strapi-tiptap-editor#22]
Since the update to `v.4.1.10` (and `v.4.1.11`) I can't open dynamic-zones containing the tiptap-editor.
I get:
<img width="700" alt="image" src="https://user-images.githubusercontent.com/23397446/168492024-fc30a582-bc76-45b8-a3fe-780cf5083f05.png">

And a white screen when built.

I've tried deleting my `yarn.lock`, `node_modules`, `build` and `.cache` folder and still the same issue occurs.

**Comment by dasmikko** [comment]
I just tested it myself with version 0.7.11 of the plugin and version 4.1.11 of strapi.

No issues for me. What version of the plugin are you using, and how is the dynamic zone setup?

**Comment by dasmikko** [comment]
Fixed in 0.7.13
