### ISSUE TITLE
cannot move cursor via arrow keys in components

### ISSUE THREAD

**Issue by kjoscha** [dasmikko/strapi-tiptap-editor#24]
When I use the plugin and add a richText field to a (repeatable) component, I cannot move the cursor via the keyboard's arrow keys, only by clicking the desired position within the text directly. When I disable the plugin, in the  default markdown editor navigation via keyboard works. Tested with strapi 4.1.7 and 4.1.11, Node 16

**Comment by birdzai** [comment]
After saving a record, I also cannot navigate a rich text field at all to edit it. The cursor is stuck at the end of the field and any attempts to move it via the keyboard or mouse doesn't seem to be working.

**Comment by dasmikko** [comment]
I'm having trouble replicating this issue. Would it be possible to setup a project, that has this issue?

**Comment by dasmikko** [comment]
Try again with version 0.8.0, i updated the tiptap library.

**Comment by JulianAtTheFrontend** [comment]
Still happens with 0.8.0, but only in repeatable components.

**Comment by dasmikko** [comment]
I just tested this again in version 0.9.0 and it seems to have been fixed now.

**Comment by dasmikko** [comment]
Re-open if issue is still there.
