### ISSUE TITLE
[question/suggestion] Link target blank

### ISSUE THREAD

**Issue by kvnhrtwg** [dasmikko/strapi-tiptap-editor#3]
Hey,

thank you for your work on this plugin, it makes using Strapi way better :) 

One question/suggestion: Could you please add the ability to decide if a link has target blank or not?

Thank you very much!

**Comment by dasmikko** [comment]
Very good idea! 

I just implemented it in 0.6.4, which I have just released now.

![image](https://user-images.githubusercontent.com/4254869/158352333-e96f5640-343c-4309-ba6a-7d9b6c8f91de.png)
