### ISSUE TITLE
[bug] Double spaces

### ISSUE THREAD

**Issue by karl-friman** [dasmikko/strapi-tiptap-editor#31]
When I insert a double space in "  " in the editor and save and go back in the editors gets very buggy. 

To recreate (using Chrome)
- Create a new post
- insert asdf asdf in the editor.
- Save and close
- Go back in. You can now select the text.
- Insert one more space in between asdf and asdf
- Save and close
- Go back in and you cannot select the text, cursor just jumps to the end.

**Comment by dasmikko** [comment]
After some digging, it seems the issue lies with my fix for the i18n issue. 

I keeps updating the content of the editor when it shouldn't.

**Comment by dasmikko** [comment]
This is fixed in version 0.8.1
