### ISSUE TITLE
[Bug] Error: Adding different instances of a keyed

### ISSUE THREAD

**Issue by coderdiaz** [dasmikko/strapi-tiptap-editor#32]
Currently, I'm using the `strapi-tiptap-editor@0.7.14` on Strapi 4.3.3 and isn't works.
I'm having this internal issue:
![image](https://user-images.githubusercontent.com/1901273/190724173-f11dfea7-48bc-4e97-85e7-928697132662.png)

**Comment by coderdiaz** [comment]
Maybe related:
https://github.com/ueberdosis/tiptap/issues/2150
https://github.com/ueberdosis/tiptap/issues/2706

**Comment by coderdiaz** [comment]
I fix the issue in my strapi server removing the yarn.lock and creating a new file to force install correct dependencies but I think the issue is happening in the last version `0.8.0`.

**Comment by dasmikko** [comment]
Is the issue still happening in the latest version `0.9.0`

**Comment by jibin2706** [comment]
> Is the issue still happening in the latest version `0.9.0`?

yes

**Comment by soubhagya-peppercontent** [comment]
> > Is the issue still happening in the latest version `0.9.0`?
> 
> yes

+

**Comment by dasmikko** [comment]
Hmm, I can't seem to reproduce this issue. I'd love to fix this, but this one is a tough one.

**Comment by jibin2706** [comment]
I'm getting this error when I try to create a new entry where the editor field is present. If the editor already has some text then it doesn't give any error.

Strapi Version - 4.3.6

![Screenshot 2022-09-22 at 12 59 10](https://user-images.githubusercontent.com/28289448/191685086-119f97b3-b9b2-40df-a01e-059aaeeb5b46.png)

**Comment by jibin2706** [comment]
To fix this bug this issue. Run this command it will fix the version issue

```
yarn remove strapi-tiptap-editor
yarn add strapi-tiptap-editor
```
