### ISSUE TITLE
[Docs] Missing releases changelog

### ISSUE THREAD

**Issue by coderdiaz** [dasmikko/strapi-tiptap-editor#33]
## Description
Hello @dasmikko, maybe it's important to make a release changelog for keep documented the changes applied in the plugin from the current `tiptap-editor` version.

If you want help,  I can help you to create a changelog section.
Cheers,

**Comment by dasmikko** [comment]
Sure, all help is welcome.

**Comment by dasmikko** [comment]
I've started tagging releases and adding changelogs.
