### ISSUE TITLE
[Feature Request] Option to remove nofollow from links

### ISSUE THREAD

**Issue by soubhagya-peppercontent** [dasmikko/strapi-tiptap-editor#34]
<img width="498" alt="image" src="https://user-images.githubusercontent.com/98809958/191427943-08245e08-a3fa-4202-8b3f-7d019e6d90f7.png">

@dasmikko 
Currently, by default all the links contain `rel="noopener noreferrer nofollow"` and there is no option to change the same in Strapi CMS.

We are facing issues in SEO as the links in the rich text editor are not crawled due to `nofollow`
Please add an option so as to change it as per requirement.

**Comment by dasmikko** [comment]
Wasn't aware that was the default value for links, and is of course a huge SEO issue.

I have now made a setting for the default rel value for links.

![image](https://user-images.githubusercontent.com/4254869/191434506-813e1c56-d602-44ef-b1ce-cd1367259981.png)

**Comment by dasmikko** [comment]
This is now release
https://github.com/dasmikko/strapi-tiptap-editor/releases/tag/0.9.0
