### ISSUE TITLE
[Bug] Multiple formatted text fields cannot be used

### ISSUE THREAD

**Issue by dennisdittrich** [dasmikko/strapi-tiptap-editor#35]
Strapi Version: 4.3.8
Tested Plugin Version: 0.9.0 , 0.8.1
Browser: Chrome, Firefox

What is the issue?

In all single types where I have inserted more than one formatted text field, only a white page appears.

Steps to Repoduce?

Add two formatted text fields to a singletype, then open this singletype to edit it. A white page appears.

When I remove the plugin, everything works fine again. After adding it, the error occurs again. Tested in a development environment and in a productive environment. (env variable)

With Plugin installed: If I delete the second text field, everythings works fine again. I add second text field error white site appears.

Error Messages?

Yes in Browser Console. 

Uncaught Error: Minified React error #301; visit https://reactjs.org/docs/error-decoder.html?invariant=301 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Data Structure:

![image](https://user-images.githubusercontent.com/25160353/191692395-3f209320-7a5f-48bc-9cad-403eb524fdf2.png)

**Comment by dasmikko** [comment]
I just tested with the latest version, that includes fixes for this issue: https://github.com/dasmikko/strapi-tiptap-editor/issues/32

I believe that fixes your issue as well, as I can't reproduce this.

Let me know if it's fixed for you as well.

**Comment by dasmikko** [comment]
I assume this is fixed as I haven't heard any response. Re-open if issue persists.
