### ISSUE TITLE
Directional keys do not work on a component

### ISSUE THREAD

**Issue by Herald-Flores** [dasmikko/strapi-tiptap-editor#40]
The arrow keys do not work in a component, when I add text to a field and try to move in the field, the arrow keys do not work.
The error only happens on fields that are added within a component, either repeatable or simple.

![image](https://user-images.githubusercontent.com/26610741/196316868-360c3df6-bb2f-4302-be6f-6f5ebab04dbb.png)

**Comment by dasmikko** [comment]
I cannot reproduce the issue. What version of the plugin are you using?

**Comment by Herald-Flores** [comment]
Hi.
The issue occurs when adding the text field inside a  Strapi component.
We are using Strapi **4.3.8** and strapi-tiptap-editor **0.9.1**

**Comment by dasmikko** [comment]
Try using the latest version of my plugin. I believe it should have been fixed.

**Comment by dasmikko** [comment]
Please re-open if issue persists with latest version of the plugin.
