### ISSUE TITLE
Ability to modify toolbar interface styles?

### ISSUE THREAD

**Issue by djmtype** [dasmikko/strapi-tiptap-editor#42]
Are the icons styled according to Strapi's design system? They are extremely difficult to make out when they're placed inside button styles. BTW, this is my main gripe with Strapi's default editor. 

Is there anyway to make the icons more approachable akin to TipTap's own website?
![Screen Shot 2022-10-18 at 5 59 39 PM](https://user-images.githubusercontent.com/930713/196553252-33fbd229-0369-4fe6-96f5-dc03e15ed1c9.png)

**Comment by djmtype** [comment]
Just reducing the padding on the `button` from `8px` to `4px` then changing the `svg` within the button to `height: 100%` and `width: 100%` makes all the difference.
![Screen Shot 2022-10-18 at 6 27 44 PM](https://user-images.githubusercontent.com/930713/196557001-90855f1a-4fe8-422a-9743-635d6a40b569.png)

**Comment by dasmikko** [comment]
I honestly agree that it would make a huge improvement! I will look into this.
