### ISSUE TITLE
Failed to add horizontal Line

### ISSUE THREAD

**Issue by devon2018** [dasmikko/strapi-tiptap-editor#43]
Getting the following error in the console when trying to add a horizontal line:

<img width="802" alt="Screenshot 2022-10-19 at 22 09 16" src="https://user-images.githubusercontent.com/46196252/196804761-58f1ae82-ea98-46dc-ac7b-44c64a20b0eb.png">

**Comment by dasmikko** [comment]
Oh my bad. Fixed in version 0.9.5
