### ISSUE TITLE
Hard breaks are not kept even if HardBreak plugin is enabled

### ISSUE THREAD

**Issue by alessmar** [dasmikko/strapi-tiptap-editor#45]
Hi,
strapi-tiptap-editor ver. 0.9.6 seems to not keep `<br>` even if HardBreak plugin is enabled (@tiptap/extension-hard-break@2.0.0-beta.199 is pulled in).

I have a field with HTML that has `<br>` but the content is displayed on a single line. If I edit it in the Tip Tap editor by splitting the content on a new line, I see that the markup applied is `<p>` and not `<br>`

**Comment by SalahAdDin** [comment]
Did you check if it is working well in a normal **TipTap Reac**t implementation?

**Comment by dasmikko** [comment]
Turns out there is a bug in the code. This is fixed in the next version.

**Comment by dasmikko** [comment]
Fixed in 0.9.7
