### ISSUE TITLE
Alt to images

### ISSUE THREAD

**Issue by thousandsofraccoons** [dasmikko/strapi-tiptap-editor#47]
Hello, thank you for a great library.
Is there any way to attach alt text to images?

**Comment by thousandsofraccoons** [comment]
Also, is there any way to define custom `rel` per each link?

**Comment by thousandsofraccoons** [comment]
One more thing - is there any way to avoid nested `<span>` tag inside `h1-h6` tags? This bug/feature causes SEO audit warning

**Comment by SalahAdDin** [comment]
@thousandsofraccoons it could be related to **Tiptap** itself.

@dasmikko is there any way to configure the **Tiptap** editor's instance?

**Comment by m7rlin** [comment]
@SalahAdDin you will have to fork this plugin and edit the code yourself.

**Comment by SalahAdDin** [comment]
> @SalahAdDin you will have to fork this plugin and edit the code yourself.

We can make a pull request and contribute to this plugin.

**Comment by m7rlin** [comment]
That's a good idea :)

**Comment by SalahAdDin** [comment]
> Also, is there any way to define custom `rel` per each link?

Is it possible to do it in Tiptap?

**Comment by thousandsofraccoons** [comment]
> > Also, is there any way to define custom `rel` per each link?
> 
> Is it possible to do it in Tiptap?

I think yes, we can assign any custom attribute to node, just need to configure the extension a little

**Comment by SalahAdDin** [comment]
in such case, we can create a pull request and help to improve this plugin.
