### ISSUE TITLE
Add support for cmd/cntrl Z (undo,redo)

### ISSUE THREAD

**Issue by tylergrow** [dasmikko/strapi-tiptap-editor#48]
Maybe I'm dumb, but CMD+Z doesn't do anything. Some undo functionality would be top

**Comment by SalahAdDin** [comment]
Doest **tiptap** have support for it?

**Comment by SalahAdDin** [comment]
> Maybe I'm dumb, but CMD+Z doesn't do anything. Some undo functionality would be top

It seems this [PR](https://github.com/dasmikko/strapi-tiptap-editor/pull/49) adds support for it.
