### ISSUE TITLE
Integration with Strapi Admin Dashboard v.4.4.6

### ISSUE THREAD

**Issue by AniketHQ** [dasmikko/strapi-tiptap-editor#50]
Hi, 
I installed the editor using 'npm i strapi-tiptap-editor' but in development mode, strapi is not picking up the editor directly. Is there any configuration needed after that in config/plugins.js?

**Comment by dasmikko** [comment]
Hi there! It should be picked up automatically.

Did you rebuild the admin dashboard?

**Comment by AniketHQ** [comment]
@dasmikko Yes, I forgot to rebuild the dashboard. Thanks again for quick resolution.
