### ISSUE TITLE
Not working with strapi version latest

### ISSUE THREAD

**Issue by fauquet-ux** [dasmikko/strapi-tiptap-editor#51]
Hello, 

strapi version : 4.5.3
tiptap version : 0.9.6
I have this error if a schema contains a richtext type =>  
![image](https://user-images.githubusercontent.com/54980565/206432407-b7ddb925-dba3-4119-9475-611521378d95.png)

Have you an issue ? 

Thanks

**Comment by markhughes** [comment]
I can confirm with 4.5.3, for reference though.. strapi-tiptap-editor is 0.9.6, the actual tiptap version is 2.0.0-beta.199 😄

**Comment by markhughes** [comment]
I have attempted to update tiptap which resolved the issue:

https://github.com/markhughes/strapi-tiptap-editor/commit/eb890b08236a7499683fe79f315f9de0e2b12576

However when testing in a monorepo I get issues with the GapCursor plugin, related to this I think: https://github.com/ueberdosis/tiptap/issues/3497

**Comment by markhughes** [comment]
<img width="903" alt="Screen Shot 2022-12-11 at 10 25 32 pm" src="https://user-images.githubusercontent.com/1357323/206900765-20920d99-c48c-4c43-890b-0c8aa38c819b.png">

Actually, there might be something more here. I cannot save the page even without the GapCursor plugin..

**Comment by SalahAdDin** [comment]
> <img alt="Screen Shot 2022-12-11 at 10 25 32 pm" width="903" src="https://user-images.githubusercontent.com/1357323/206900765-20920d99-c48c-4c43-890b-0c8aa38c819b.png">
> 
> Actually, there might be something more here. I cannot save the page even without the GapCursor plugin..

@dasmikko it seems something is going wrong when saving the object.

**Comment by msadcenko** [comment]
Is someone working on a fix? We would use strapi latest + this tip tap plugin

**Comment by dasmikko** [comment]
I can confirm that it works fine with latest version of strapi. Do not hesitate to re-open this, or a new ticket if it stops working again.
