### ISSUE TITLE
Not working with Node 18 (last LTS)

### ISSUE THREAD

**Issue by mastepanoski** [dasmikko/strapi-tiptap-editor#52]
I got the following error:  _strapi-tiptap-editor@0.9.6: The engine "node" is incompatible with this module. Expected version ">=12.x.x <=16.x.x". Got "18.12.1"_

**Comment by dasmikko** [comment]
I have made a fix for this, that will be available in the next release.

**Comment by dasmikko** [comment]
Fixed in 0.9.7
