### ISSUE TITLE
Not working with strapi 4.6.0

### ISSUE THREAD

**Issue by marcinsz84** [dasmikko/strapi-tiptap-editor#59]
`warning "strapi-tiptap-editor > @strapi/icons@1.5.0" has unmet peer dependency "react@^17.0.1".
warning "strapi-tiptap-editor > @strapi/icons@1.5.0" has unmet peer dependency "react-dom@^17.0.1".
warning "strapi-tiptap-editor > @tiptap/extension-code-block@2.0.0-beta.209" has unmet peer dependency "prosemirror-state@^1.4.1".
warning "strapi-tiptap-editor > @tiptap/extension-horizontal-rule@2.0.0-beta.209" has unmet peer dependency "prosemirror-state@^1.4.1".
warning "strapi-tiptap-editor > @tiptap/extension-link@2.0.0-beta.209" has unmet peer dependency "prosemirror-model@^1.18.1".
warning "strapi-tiptap-editor > @tiptap/extension-link@2.0.0-beta.209" has unmet peer dependency "prosemirror-state@^1.4.1".
warning "strapi-tiptap-editor > @tiptap/extension-character-count@2.0.0-beta.209" has unmet peer dependency "prosemirror-model@^1.18.1".
warning "strapi-tiptap-editor > @tiptap/extension-character-count@2.0.0-beta.209" has unmet peer dependency "prosemirror-state@^1.4.1".
warning "strapi-tiptap-editor > @tiptap/extension-gapcursor@2.0.0-beta.209" has unmet peer dependency "prosemirror-gapcursor@^1.3.1".
warning "strapi-tiptap-editor > @tiptap/core@2.0.0-beta.209" has unmet peer dependency "prosemirror-commands@^1.3.1".
warning "strapi-tiptap-editor > @tiptap/core@2.0.0-beta.209" has unmet peer dependency "prosemirror-keymap@^1.2.0".
warning "strapi-tiptap-editor > @tiptap/core@2.0.0-beta.209" has unmet peer dependency "prosemirror-model@^1.18.1".
warning "strapi-tiptap-editor > @tiptap/core@2.0.0-beta.209" has unmet peer dependency "prosemirror-schema-list@^1.2.2".
warning "strapi-tiptap-editor > @tiptap/core@2.0.0-beta.209" has unmet peer dependency "prosemirror-state@^1.4.1".
warning "strapi-tiptap-editor > @tiptap/core@2.0.0-beta.209" has unmet peer dependency "prosemirror-transform@^1.7.0".
warning "strapi-tiptap-editor > @tiptap/core@2.0.0-beta.209" has unmet peer dependency "prosemirror-view@^1.28.2".
warning "strapi-tiptap-editor > react-icons@4.7.1" has unmet peer dependency "react@*".
warning "strapi-tiptap-editor > @tiptap/react@2.0.0-beta.209" has unmet peer dependency "react@^17.0.0 || ^18.0.0".
warning "strapi-tiptap-editor > @tiptap/react@2.0.0-beta.209" has unmet peer dependency "react-dom@^17.0.0 || ^18.0.0".
warning "strapi-tiptap-editor > @tiptap/extension-table@2.0.0-beta.209" has unmet peer dependency "@tiptap/prosemirror-tables@^1.1.3".
warning "strapi-tiptap-editor > @tiptap/extension-table@2.0.0-beta.209" has unmet peer dependency "prosemirror-model@^1.18.1".
warning "strapi-tiptap-editor > @tiptap/extension-table@2.0.0-beta.209" has unmet peer dependency "prosemirror-state@^1.4.1".
warning "strapi-tiptap-editor > @tiptap/extension-table@2.0.0-beta.209" has unmet peer dependency "prosemirror-view@^1.28.2".
warning "strapi-tiptap-editor > @tiptap/react > @tiptap/extension-bubble-menu@2.0.0-beta.209" has unmet peer dependency "prosemirror-state@^1.4.1".
warning "strapi-tiptap-editor > @tiptap/react > @tiptap/extension-floating-menu@2.0.0-beta.209" has unmet peer dependency "prosemirror-state@^1.4.1".`

Even after installing all dependencies are still not working, causing a blank page in the Strapi admin panel after picking editor content.

**Comment by garbusbeach** [comment]
I've come to the same issue.
