### ISSUE TITLE
Please add support for Base64 Image

### ISSUE THREAD

**Issue by Brandyweb** [dasmikko/strapi-tiptap-editor#6]
Hello thanks for taking this package to Strapi, but I am in a problem since we are using base64 in some images but the editor removes them according to the doc should I add this https://tiptap.dev/api/nodes/image#allow-base64:
 ```
ImageExtension.configure({
      inline: true,
      allowBase64: true,
}),
```
 to the Image config, or is there any way I can add these config from strapi without having to modify the code?

**Comment by dasmikko** [comment]
Hi, thanks for making an issue!

I'm in the middle of making the plugin configurable via the straps interface so i will make sure you can enable this.

**Comment by Brandyweb** [comment]
Thank's good work!

**Comment by dasmikko** [comment]
Hi! 

In the latest update, i have added support for the base64 setting, but I still need to implement a dialog where you add a image via base64 string.

I'm working on this feature now.

**Comment by Brandyweb** [comment]
Wow this is really cool!

**Comment by dasmikko** [comment]
Alright, sorry for the wait, but with the 0.7.7 release, the editor now fully supports base64 images!

![image](https://user-images.githubusercontent.com/4254869/163165100-8a7d08b3-02c7-468b-8c73-c8259779eb23.png)
