### ISSUE TITLE
Editor is not detecting changes when typing

### ISSUE THREAD

**Issue by mariojsnunes** [dasmikko/strapi-tiptap-editor#61]
versions:
"@strapi/strapi": "4.6.1",
"strapi-tiptap-editor": "^0.9.10"

When I type on the editor, the save button stays grey (no changes).
If I also change another field, the save button is enabled, but when I click save, the editor text is not saved.

My guess is that it's not updating the model.
I can force it to detect changes by selecting text and clicking clicking on the buttons (bold, italic, etc)

**Comment by aw-gerrit** [comment]
same here

**Comment by dasmikko** [comment]
I'm having some trouble replicating this issue. Can you make a project that has this issue?

**Comment by Taylor-Hinote** [comment]
Same problem here but I found a work around

While typing or editing all functions act normal but won't allow you to save changes, I hit the center align button after highlighting some basic content I then can set that content back to what ever I had it previous and then saving works fines

![tiptapBug](https://user-images.githubusercontent.com/117930865/222830382-7c35efca-f65c-4f5c-8e15-147244d0dc19.gif)

**Comment by mastepanoski** [comment]
The same issue happens when an image is inserted. The editor does not detect the change.

**Comment by VercammenJens** [comment]
Same issue here and can't really downgrade to a previous package because the strapi build always fails then.

**Comment by VercammenJens** [comment]
@dasmikko Been investigating a little bit by cloning the package and testing local. Haven't tried replicating the issue yet. What I've currently found is that on every update/change there is a error in the console. (possibly a dependency issue?) 

I've tried logging the `ctx` & `settings` inside the `onUpdate` function in `Wysiywg/index.js` but this code is never reached.

```
    onUpdate(ctx) {
      console.log(settings)
      console.log(ctx)
      if (settings.other.saveJson) {
        onChange({target: {name, value: JSON.stringify(ctx.editor.getJSON())}})
      } else {
        onChange({target: {name, value: ctx.editor.getHTML()}})
      }
    },
```

It's my first time kind of trying to contributing to an open source package, so I'm not really sure how to debug it other than adding logs here and there. Tips are always welcome!

All this happens on version `0.9.10` & `0.9.11` of strapi-tiptap-editor and strapi version `4.7.1`, but I guess the strapi version isn't a big impact on this. I'll also add an image of the minified error message:
<img width="415" alt="Screenshot 2023-03-16 at 15 56 16" src="https://user-images.githubusercontent.com/19661051/225697615-edf79f89-35dc-4c86-b429-0f3581960a25.png">

**Comment by xbeakmanx** [comment]
same here

**Comment by marcinsz84** [comment]
Same here on `"@strapi/strapi": "4.8.2"` and `"strapi-tiptap-editor": "^0.9.11"`

**Comment by marcinsz84** [comment]
@dasmikko Works well, thanks.
