### ISSUE TITLE
[BUG] Missing dep @tiptap/pm on version "^0.7.3" and up

### ISSUE THREAD

**Issue by jpizzati-uvl** [dasmikko/strapi-tiptap-editor#62]
Today I was revisiting a previously working Strapi project and ran into this error when trying to build my Strapi app:

**Steps to reproduce:**
- Install dependencies
- Run yarn build

**Versions:**
"@strapi/strapi": "4.4.1",
"strapi-tiptap-editor": "^0.9.10"

**Error:**
#0 7.745 ModuleNotFoundError: Module not found: Error: Can't resolve '@tiptap/pm/state' in '/opt/node_modules/strapi-tiptap-editor/node_modules/@tiptap/extension-floating-menu/dist'

I tried a couple things like upgrading package version or trying install with npm but the only thing that seemed to work was installing missing dep, although I don't think this is ideal: 

"@tiptap/pm": "^2.0.0-beta.217",

**Comment by dasmikko** [comment]
It's weird that you have to install it manually, as @tiptap/pm is a dependency in the latest version of my plugin.

**Comment by dasmikko** [comment]
Is this still an issue in the latest version?

**Comment by jpizzati-uvl** [comment]
> Is this still an issue in the latest version?

Solved! Error no longer appears. Thanks.
