### ISSUE TITLE
Tiptip not focusable

### ISSUE THREAD

**Issue by Clex1o1** [dasmikko/strapi-tiptap-editor#63]
Hello  installed the tiptap plugin into my alomost fresh strapi: Node 18 Strapi 4.6.1 and  strapi-tiptap-editor 0.9.10. If I click inside a editor field I get this error message:
`Object is not a function (near '...tippy_js__WEBPACK_IMPORTED_MODULE_2__...')`

I start strapi with `strapi build --no-optimization && strapi develop --watch-admin` for better debugging. I can see error in webpacked files then. 

Any ideas?

**Comment by dasmikko** [comment]
I can't seem to seem figure out why this happens. It could be an issue with strapis webpack setup.

**Comment by dasmikko** [comment]
Please reopen if still an issue.
