### ISSUE TITLE
Warning with Node.js 20 (latest LTS)

### ISSUE THREAD

**Issue by illright** [dasmikko/strapi-tiptap-editor#70]
If I install the plugin with npm when running Node.js 20, I get an `EBADENGINE`:
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'strapi-tiptap-editor@0.9.12',
npm WARN EBADENGINE   required: { node: '>=12.x.x <=18.x.x', npm: '>=6.0.0' },
npm WARN EBADENGINE   current: { node: 'v20.8.0', npm: '10.1.0' }
npm WARN EBADENGINE }
```

**Comment by shaital** [comment]
yarn config set ignore-engines true

**Comment by CamilleHbp** [comment]
Thanks for a solution, but the package should update the node version since it's compatible with it :)

**Comment by dasmikko** [comment]
> Thanks for a solution, but the package should update the node version since it's compatible with it :)

I just pushed a new version that should fix this.
